replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 10m
    memory: 64Mi

liveness:
  path: /liveness/ping
  initialDelaySeconds: 200
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10
readiness:
  path: /liveness/ping
  initialDelaySeconds: 200
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 10

applicationProperties: |-
  application.timezone.id=UTC
  application.locale.tag=it-IT

  spring.datasource.driver-class-name=com.mysql.jdbc.Driver
  spring.datasource.url=jdbc:mysql://st-db-mysql-enhanced-ope.st.svc.cluster.local:3306/enhop_shift_handover_logbook?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
  spring.datasource.username=${APP_DB_USERNAME}
  spring.datasource.password=${APP_DB_PASSWORD}
  #spring.jpa.properties.hibernate.show_sql=true

  microservice.users.baseaddress=http://st-be-user-management-service-eo-1-0-0-spring-boot.st.svc.cluster.local:8080/users
  microservice.userexport.baseaddress=http://st-be-user-management-service-eo-1-0-0-spring-boot.st.svc.cluster.local:8080/export
  microservice.files.baseaddress=http://st-be-file-management-service-eo-1-0-0-spring-boot.st.svc.cluster.local:8080/
  microservice.files.baseaddress.external=http://st-be-file-management-service-eo-1-0-0-spring-boot.st.svc.cluster.local:8080/

applicationSecrets:
  app.db.username: enhop_shift_handover_logbook
  app.db.password: 3nh0p!
